package io.github.strikeless.neptunium.setting;

import com.google.gson.JsonElement;
import io.github.strikeless.neptunium.setting.holder.SettingHolder;
import io.github.strikeless.neptunium.util.interfaces.InstanceAccessor;
import io.github.strikeless.neptunium.util.interfaces.Named;
import lombok.Data;

/**
 * @author Strikeless
 * @since 07.07.2022
 */
@Data
public abstract class Setting<T> implements InstanceAccessor, Named {

    private final SettingHolder parent;

    // The getter for the Named interface is automatically generated by lombok
    private final String name;

    private T value;

    public Setting(final SettingHolder parent, final String name, final T value) {
        this.parent = parent;
        this.name = name;
        this.setValue(value);

        // It would probably be better practice to add child-settings in the moduloid instead of the setting itself,
        // but that would make creating settings a slight bit more complex (usage of an addValue method for example),
        // and we already have the parent moduloid's instance here.
        this.parent.getSettings().add(this);
    }

    public abstract JsonElement serialize();

    public abstract void deserialize(final JsonElement serialized);
}
